Add more pipi checks and adaptations for multiple sources

diff --git a/pipiCam b/pipiCam
--- a/pipiCam
+++ b/pipiCam
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# for i in {start..end..step} ; do echo -ne "$i " ; bash pipiCam $i ; sleep 3 ; done
+
 if [ $# -lt 1 ]; then
   echo "Usage: $0 <config>"
   exit 1
@@ -10,18 +12,32 @@ fi
 cfg=$1
 
 # TODO: Fix L, ml, mh from path
-L=24
-Lattice="24.24.24.64"
+L=32
+Lattice="32.32.32.64"
 path=`pwd`
-tag=L${L}_l0.15_h0.15
+tag=L${L}_l0.015_h0.15
 
 # Adjustable parameters
-# 32 cores in 1x2=2 tasks with 24x24x24x32 per task
-N=1
+# 512 cores in 16x2=32 tasks with 16x16x16x16 per task
+N=16
 per_node=2
 per_task=16
-MPIGrid="1.1.1.2"
-time=10:00:00
+MPIGrid="2.2.2.4"
+time=09:00:00
+
+# 256 cores in 8x2=16 tasks with 32x16x16x16 per task
+N=8
+per_node=2
+per_task=16
+MPIGrid="1.2.2.4"
+time=18:00:00
+
+# 128 cores in 4x2=8 tasks with 32x32x16x16 per task
+N=4
+per_node=2
+per_task=16
+MPIGrid="1.1.2.4"
+time=36:00:00
 
 # Same modules as when compiling
 module unload intel/bundles/complib/2017.4
@@ -34,7 +50,6 @@ tasks=`echo $N | awk -v each="$per_node" '{print($1*each)}'`
 temp=submit.$cfg
 echo "#!/bin/bash" > $temp
 echo "#SBATCH -p skylake" >> $temp
-#echo "#SBATCH -p cclake" >> $temp # Dies: BAK/out.pipi.47725517
 echo "#SBATCH -A dirac-dp162-CPU" >> $temp
 echo "#SBATCH -N $N" >> $temp
 echo "#SBATCH --ntasks-per-node=$per_node" >> $temp
@@ -59,18 +74,32 @@ echo "echo 'Machine info'" >> $temp
 echo "sinfo -s" >> $temp
 
 echo "echo '=====================JOB STARTING=========================='" >> $temp
+
 # Check that we're not going to break anything,
 # Maybe add checks for the meson and pion correlators?
 latPrefix=$path/Configs/ckpoint_lat
-lat=${latPrefix}.${cfg}
-out=Out/pipi.$cfg
+lat=$latPrefix.$cfg
+out=Out/pipi.t8.$cfg # TODO: Read in source time as input parameter
+mes=mesons/wall_ll.t8.$cfg.h5
+two=pipi/wall_llll.t8.$cfg.h5
 if [ ! -e $lat ]; then
-  echo "Error: lattice $lat not found"
+  echo "Error: lattice not found"
+  echo "file: $lat"
   rm -f $temp
   exit 1
 fi
 if [ -e $out ]; then
   echo "Error: output file $out exists"
+  rm -f $temp
+  exit 1
+fi
+if [ -e $mes ]; then
+  echo "Error: output file $mes exists"
+  rm -f $temp
+  exit 1
+fi
+if [ -e $two ]; then
+  echo "Error: output file $two exists"
   rm -f $temp
   exit 1
 fi
@@ -81,18 +110,20 @@ if [ ! -e base.xml ]; then
 fi
 
 # Set up XML parameters for this job
-cp -f base.xml xml.$cfg
+cp -f base.xml xml.t8.$cfg
 cfgEnd=$((cfg+1))
-sed -i "s/_CONFIG_START_/${cfg}/g" xml.$cfg
-sed -i "s/_CONFIG_END_/${cfgEnd}/g" xml.$cfg
-sed -i "s/_RUN_ID_/${tag}/g" xml.$cfg
-sed -i "s#_CONFIG_PREFIX_#${latPrefix}#g" xml.$cfg
+sed -i "s/_CONFIG_START_/${cfg}/g" xml.t8.$cfg
+sed -i "s/_CONFIG_END_/${cfgEnd}/g" xml.t8.$cfg
+sed -i "s/_RUN_ID_/${tag}/g" xml.t8.$cfg
+sed -i "s#_CONFIG_PREFIX_#${latPrefix}#g" xml.t8.$cfg
 
 # Go
 echo "echo \"Job pipi.$cfg started \"\`date\`\" jobid \$SLURM_JOBID\" >> $out" >> $temp
 echo "echo \"=== Running MPI application on $cores cpus ===\" >> $out" >> $temp
-echo "echo \"srun --mpi=pmi2 -n $tasks $bin xml.$cfg --grid $Lattice --mpi $MPIGrid --threads $per_task --comms-concurrent --comms-overlap --shm 2048\" >> $out" >> $temp
-echo "srun --mpi=pmi2 -n $tasks $bin xml.$cfg --grid $Lattice --mpi $MPIGrid --threads $per_task --comms-concurrent --comms-overlap --shm 2048 >> $out" >> $temp
+echo "echo \"srun --mpi=pmi2 -n $tasks $bin xml.t8.$cfg --grid $Lattice --mpi $MPIGrid --threads $per_task --comms-concurrent --comms-overlap --shm 2048\" >> $out" >> $temp
+echo "srun --mpi=pmi2 -n $tasks $bin xml.t8.$cfg --grid $Lattice --mpi $MPIGrid --threads $per_task --comms-concurrent --comms-overlap --shm 2048 >> $out" >> $temp
+echo "mv -iv mesons/wall_ll.$cfg.h5 $mes" >> $temp
+echo "mv -iv pipi/wall_llll.$cfg.h5 $two" >> $temp
 echo "echo \"=== MPI application finished at \"\`date\`\" ===\" >> $out" >> $temp
 echo "echo '========================ALL DONE==========================='" >> $temp
 
diff --git a/pipiCosma b/pipiCosma
--- a/pipiCosma
+++ b/pipiCosma
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# for i in {start..end..step} ; do echo -ne "$i " ; bash pipiCosma $i ; sleep 3 ; done
+
 if [ $# -lt 1 ]; then
   echo "Usage: $0 <config>"
   exit 1
@@ -64,18 +66,32 @@ echo "echo 'Machine info'" >> $temp
 echo "sinfo -s" >> $temp
 
 echo "echo '=====================JOB STARTING=========================='" >> $temp
+
 # Check that we're not going to break anything,
 # Maybe add checks for the meson and pion correlators?
 latPrefix=$path/Configs/ckpoint_lat
-lat=${latPrefix}.${cfg}
-out=Out/pipi.$cfg
+lat=$latPrefix.$cfg
+out=Out/pipi.t40.$cfg # TODO: Read in source time as input parameter
+mes=mesons/wall_ll.t40.$cfg.h5
+two=pipi/wall_llll.t40.$cfg.h5
 if [ ! -e $lat ]; then
-  echo "Error: lattice $lat not found"
+  echo "Error: lattice not found"
+  echo "file: $lat"
   rm -f $temp
   exit 1
 fi
 if [ -e $out ]; then
   echo "Error: output file $out exists"
+  rm -f $temp
+  exit 1
+fi
+if [ -e $mes ]; then
+  echo "Error: output file $mes exists"
+  rm -f $temp
+  exit 1
+fi
+if [ -e $two ]; then
+  echo "Error: output file $two exists"
   rm -f $temp
   exit 1
 fi
@@ -86,18 +102,20 @@ if [ ! -e base.xml ]; then
 fi
 
 # Set up XML parameters for this job
-cp -f base.xml xml.$cfg
+cp -f base.xml xml.t40.$cfg
 cfgEnd=$((cfg+1))
-sed -i "s/_CONFIG_START_/${cfg}/g" xml.$cfg
-sed -i "s/_CONFIG_END_/${cfgEnd}/g" xml.$cfg
-sed -i "s/_RUN_ID_/${tag}/g" xml.$cfg
-sed -i "s#_CONFIG_PREFIX_#${latPrefix}#g" xml.$cfg
+sed -i "s/_CONFIG_START_/${cfg}/g" xml.t40.$cfg
+sed -i "s/_CONFIG_END_/${cfgEnd}/g" xml.t40.$cfg
+sed -i "s/_RUN_ID_/${tag}/g" xml.t40.$cfg
+sed -i "s#_CONFIG_PREFIX_#${latPrefix}#g" xml.t40.$cfg
 
 # Go
 echo "echo \"Job pipi.$cfg started \"\`date\`\" jobid \$SLURM_JOBID\" >> $out" >> $temp
 echo "echo \"=== Running MPI application on $cores cpus ===\" >> $out" >> $temp
-echo "echo \"srun --mpi=pmi2 -n $tasks $bin xml.$cfg --grid $Lattice --mpi $MPIGrid --threads $per_task --comms-concurrent --comms-overlap --shm 2048\" >> $out" >> $temp
-echo "srun --mpi=pmi2 -n $tasks $bin xml.$cfg --grid $Lattice --mpi $MPIGrid --threads $per_task --comms-concurrent --comms-overlap --shm 2048 >> $out" >> $temp
+echo "echo \"srun --mpi=pmi2 -n $tasks $bin xml.t40.$cfg --grid $Lattice --mpi $MPIGrid --threads $per_task --comms-concurrent --comms-overlap --shm 2048\" >> $out" >> $temp
+echo "srun --mpi=pmi2 -n $tasks $bin xml.t40.$cfg --grid $Lattice --mpi $MPIGrid --threads $per_task --comms-concurrent --comms-overlap --shm 2048 >> $out" >> $temp
+echo "mv -iv mesons/wall_ll.$cfg.h5 $mes" >> $temp
+echo "mv -iv pipi/wall_llll.$cfg.h5 $two" >> $temp
 echo "echo \"=== MPI application finished at \"\`date\`\" ===\" >> $out" >> $temp
 echo "echo '========================ALL DONE==========================='" >> $temp
 
