Some QHMC parsing generalizations to handle both SU(4) 4f and SU(3) 8f

diff --git a/update_qhmc b/update_qhmc
--- a/update_qhmc
+++ b/update_qhmc
@@ -6,8 +6,16 @@ if [ $# != 0 ]; then
 fi
 
 temp=`pwd`
-dir=${temp##*FA/}   # Strip everything up to and including "FA/"
-path=/data/lsd/KS_nHYP_FA/$dir
+if [[ $temp == *"KS_nHYP_FA"* ]] ; then
+  dir=${temp##*FA/}   # Strip everything up to and including "FA/"
+  path=/data/lsd/KS_nHYP_FA/$dir
+elif [[ $temp == *"SU4"* ]] ; then
+  dir=${temp##*4f/}   # Strip everything up to and including "4f/"
+  path=/data/lsd/SU4/4f/$dir
+else
+  echo "ERROR: Unrecognized path $temp"
+  exit 1
+fi
 # ------------------------------------------------------------------
 
 
diff --git a/writeLSD b/writeLSD
--- a/writeLSD
+++ b/writeLSD
@@ -8,7 +8,14 @@ fi
 tag=$1
 date=$2
 
-out="/data/lsd/KS_nHYP_FA/$tag/index.html"
+if [ -d "/data/lsd/KS_nHYP_FA/$tag" ] ; then
+  out="/data/lsd/KS_nHYP_FA/$tag/index.html"
+elif [ -d "/data/lsd/SU4/4f/$tag" ] ; then
+  out="/data/lsd/SU4/4f/$tag/index.html"
+else
+  echo "ERROR: Can't find appropriate $tag directory"
+  exit 1
+fi
 #echo "Writing $out"
 
 echo '<html><head>' > $out
